# Generated by Django 5.0.3 on 2024-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(max_length=500),
        ),
    ]
