# Generated by Django 5.0.3 on 2024-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='park',
            field=models.CharField(choices=[('CyberPark', 'CyberPark'), ('InfoPark', 'InfoPark'), ('TechnoPark', 'TechnoPark')], default='CyberPark', max_length=100),
        ),
    ]
