# Generated by Django 5.0.3 on 2024-08-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobs_company_name_alter_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=500),
        ),
    ]
