# Generated by Django 5.0.3 on 2024-08-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobs_job_location_alter_jobs_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
    ]
