# Generated by Django 5.0.3 on 2024-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_jobs_job_type_remove_jobs_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnoparkJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_listing_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AllJobs',
        ),
    ]
