# Generated by Django 5.0.3 on 2024-08-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_technoparkjobs_delete_alljobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='technoparkjobs',
            name='logo',
            field=models.FileField(null=True, upload_to='Technopark Company Jobs'),
        ),
    ]
