# Generated by Django 5.0.3 on 2024-08-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_technoparkjobs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technoparkjobs',
            name='job_listing_id',
            field=models.CharField(max_length=100),
        ),
    ]
