# Generated by Django 5.0.3 on 2024-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_technoparkjobs_job_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technoparkjobs',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='technoparkjobs',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
