# Generated by Django 5.0.3 on 2024-08-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_technoparkjobs_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberparkJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField()),
                ('job_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('job_link', models.URLField()),
                ('post_date', models.DateField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
