# Generated by Django 5.0.3 on 2024-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cyberparkjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='post_date',
            field=models.CharField(max_length=200),
        ),
    ]
