# Generated by Django 5.0.3 on 2024-08-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_cyberparkjobs_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='job_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='post_date',
            field=models.CharField(max_length=500),
        ),
    ]
