# Generated by Django 5.0.3 on 2024-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_cyberparkjobs_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='job_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='job_title',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='post_date',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='cyberparkjobs',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
