# Generated by Django 5.0.3 on 2024-08-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_cyberparkjobs_job_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberparkjobs',
            name='title',
        ),
    ]
