# Generated by Django 5.0.3 on 2024-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_cyberparkjobs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoparkJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField()),
                ('job_title', models.CharField(max_length=600)),
                ('job_link', models.TextField()),
                ('post_date', models.CharField(max_length=600)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='IndeedJobs',
        ),
    ]
